name: Tag version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get version from package.json
        id: get-version
        run: echo "::set-output name=version::$(jq -r .version package.json)"
      - name: check if version has changed
        id: check-version
        uses: EndBug/version-check@v2
        with:
          diff-search: true
      - name: create tag if version has changed
        if: steps.check-version.outputs.changed == 'true'
        run: |
          git config user.name ivy-github-actions
          git config user.email ivy@pinnacle.us.org
          git tag v${{ steps.get-version.outputs.version }}
          git push origin v${{ steps.get-version.outputs.version }}
